# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csample.proto\"G\n\x06Outlet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\"\x93\x01\n\x0cRouteRequest\x12\x0f\n\x07num_dse\x18\x01 \x01(\x05\x12\x14\n\x0cmax_distance\x18\x02 \x01(\x05\x12\x12\n\nmax_outlet\x18\x03 \x01(\x05\x12\x17\n\x0fstart_locations\x18\x04 \x03(\x05\x12\x15\n\rend_locations\x18\x05 \x03(\x05\x12\x18\n\x07outlets\x18\x06 \x03(\x0b\x32\x07.Outlet\")\n\rRouteResponse\x12\x18\n\x07outlets\x18\x01 \x03(\x0b\x32\x07.Outlet2;\n\x0eRouteGenerator\x12)\n\x08Generate\x12\r.RouteRequest\x1a\x0e.RouteResponseb\x06proto3'
)




_OUTLET = _descriptor.Descriptor(
  name='Outlet',
  full_name='Outlet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Outlet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Outlet.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Outlet.latitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Outlet.longitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=87,
)


_ROUTEREQUEST = _descriptor.Descriptor(
  name='RouteRequest',
  full_name='RouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_dse', full_name='RouteRequest.num_dse', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_distance', full_name='RouteRequest.max_distance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_outlet', full_name='RouteRequest.max_outlet', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_locations', full_name='RouteRequest.start_locations', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_locations', full_name='RouteRequest.end_locations', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outlets', full_name='RouteRequest.outlets', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=237,
)


_ROUTERESPONSE = _descriptor.Descriptor(
  name='RouteResponse',
  full_name='RouteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='outlets', full_name='RouteResponse.outlets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=280,
)

_ROUTEREQUEST.fields_by_name['outlets'].message_type = _OUTLET
_ROUTERESPONSE.fields_by_name['outlets'].message_type = _OUTLET
DESCRIPTOR.message_types_by_name['Outlet'] = _OUTLET
DESCRIPTOR.message_types_by_name['RouteRequest'] = _ROUTEREQUEST
DESCRIPTOR.message_types_by_name['RouteResponse'] = _ROUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Outlet = _reflection.GeneratedProtocolMessageType('Outlet', (_message.Message,), {
  'DESCRIPTOR' : _OUTLET,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:Outlet)
  })
_sym_db.RegisterMessage(Outlet)

RouteRequest = _reflection.GeneratedProtocolMessageType('RouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:RouteRequest)
  })
_sym_db.RegisterMessage(RouteRequest)

RouteResponse = _reflection.GeneratedProtocolMessageType('RouteResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTERESPONSE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:RouteResponse)
  })
_sym_db.RegisterMessage(RouteResponse)



_ROUTEGENERATOR = _descriptor.ServiceDescriptor(
  name='RouteGenerator',
  full_name='RouteGenerator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=282,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='Generate',
    full_name='RouteGenerator.Generate',
    index=0,
    containing_service=None,
    input_type=_ROUTEREQUEST,
    output_type=_ROUTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTEGENERATOR)

DESCRIPTOR.services_by_name['RouteGenerator'] = _ROUTEGENERATOR

# @@protoc_insertion_point(module_scope)
